version: '3'

volumes:
  local_postgres_data: { }
  local_elasticsearch_data: { }

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0

#  celeryworker:
#    <<: *django
#    ports: [ ]
#    command: celery -A config worker -l info
#
#  celerybeat:
#    <<: *django
#    ports: [ ]
#    command: celery -A config beat -l info